### ISSUE TITLE
Not using the same GPU as pytorch because pytorch device id doesn't match nvidia-smi id without setting environment variable. What is a good way to select gpu_id for experiments?

### ISSUE THREAD

**Issue by jmhsi** [stas00/ipyexperiments#2]
Hi there. I think IPyExperiments is pretty cool, but I'm finding that IPyExperiment is not grabbing the same GPU as pytorch.

For more context, I have two GPUs but I only use one since I'm doing some neural style transfer via optimization and don't have multiple batches so it doesn't look like nn.DataParallel would help me.

**Originally:**
I have a 1060 and a 1080ti, and pytorch grabs my 1080ti and calls it gpu id 0. However, nvidia-smi calls my 1080ti gpu 1. See attached screenshots.

<img width="676" alt="screen shot 2019-01-03 at 3 27 40 pm" src="https://user-images.githubusercontent.com/12853718/50667147-d4a55380-0f6c-11e9-8baf-e3dc3adb5fe9.png">
<img width="564" alt="screen shot 2019-01-03 at 3 28 02 pm" src="https://user-images.githubusercontent.com/12853718/50667153-d838da80-0f6c-11e9-812e-379c819e5edc.png">
<img width="662" alt="screen shot 2019-01-03 at 3 28 43 pm" src="https://user-images.githubusercontent.com/12853718/50667162-dcfd8e80-0f6c-11e9-8ec1-71a3fec705c0.png">

AlbanD's answer and SO explained why the ID mismatch: (CUDA order by default is sorting by computing power rather than bus-id which is what nvidia-smi shows)
https://discuss.pytorch.org/t/gpu-devices-nvidia-smi-and-cuda-get-device-name-output-appear-inconsistent/13150
https://stackoverflow.com/questions/52815708/order-of-cuda-devices

**After setting the bus-id environment variable**
torch.cuda.current_device() now shows 0 and matches with the nvidia-smi ordering.
<img width="661" alt="screen shot 2019-01-03 at 4 08 03 pm" src="https://user-images.githubusercontent.com/12853718/50668165-3ddb9580-0f72-11e9-81a1-f79fca585c2b.png">

Currently in line 34 of ipyexperiments.py I see that GPU id is always returning 0 from the lambda function, and I see that the global is being used in the backend for pytorch and I'm assuming that's how the device id is being grabbed. Perhaps it should be changed accept a torch.device and take the torch.device.index? 
```device = torch.device("cuda:1" if torch.cuda.is_available() else "cpu")```
``` with IPyExperiments(device):```
 Or maybe something like
```with IPyExperiments(gpu_id=1):```
What do you think?

**Comment by stas00** [comment]
Thanks for your detailed report and suggestions, @jmhsi. Unfortunately, I only have one gpu at the moment, hence I'm not surprised the module has problems on multiple gpu setup.

1. wrt picking the correct ID

The lambda returning 0 is just the default. the pytorch backend sets it to `torch.cuda.current_device()`. Shouldn't it return the correct ID once you setup torch.device("cuda:1")?

`gpu_current_device = torch.cuda.current_device`

Perhaps there is a bug in the code and `gpu_current_device()` currently always returns 0?

It probably should print out the ID `torch.cuda.current_device` returned to make it non-ambiguous.

2. wrt different ordering of IDs (nvidia-smi vs. default pytorch). 

If `torch.cuda.current_device()` does the right thing, i.e. returning the current device, the experiment will be run on the device that you setup before running it. In which case it's up to the user to setup any order they want (and I would be happy to document the specifics, based on the links you have shared). That's a very important information.

That's why I'm not sure why would you need to specify `IPyExperiments(gpu_id)`.

**Comment by stas00** [comment]
If you `pip install git+https://github.com/stas00/ipyexperiments.git` it now reports the info about the card it chose via `torch.cuda.current_device`:

```
*** Loading backend: pytorch
Device: ID 0, GeForce GTX 1070 Ti (7.9 GB RAM)
```

**Comment by jmhsi** [comment]
Hmm nevermind. I found that it does work properly with torch.cuda.set_device().

**Comment by stas00** [comment]
Good point, @jmhsi! I will make sure to document this nuance. Thank you for your feedback.

**Comment by jmhsi** [comment]
Its looking good.
<img width="746" alt="screen shot 2019-01-04 at 12 11 15 pm" src="https://user-images.githubusercontent.com/12853718/50708648-f14b9500-1019-11e9-9abe-100602aba551.png">

**Comment by stas00** [comment]
Perfect. Thank you for validating the new version, @jmhsi.
